### ISSUE TITLE
banking.php page not displaying fully

### ISSUE THREAD

**Issue by KwameMax17** [Tonemon/UBank#5]
I believe I have done everything correctly but when I login into either the STAFF or NORMAL ACCOUNTS the banking.php page just display header and not the complete fully body of the page
![Screenshot_20190919-112725](https://user-images.githubusercontent.com/40938165/65240325-81f6d200-dad0-11e9-9cc8-81e34f42be4d.png)
![Screenshot_20190919-112707](https://user-images.githubusercontent.com/40938165/65240339-8a4f0d00-dad0-11e9-8e0d-97b53a6e5d20.png)

**Comment by Tonemon** [comment]
That's weird... Could you open the page in a desktop browser and show the page source (right click -> view page source)? I wonder what's going on behind the page.

EDIT: I can see that you successfully setup the databases and users because of the 2 messages (top right), but I can't see why it shouldn't work.

**Comment by KwameMax17** [comment]
Don't worry, I managed to fix this. "MYSQL" isn't working in PHP7 so I had to change it to "MYSQLI" but this needs two parameter so I had to put this "$var(or any name) = mysqli_connect($serverName,$dbusername,$dbpassword);" into "dbconn.php" and add "$var" as a parameter in "MYSQLI"

**Comment by Tonemon** [comment]
Great! If you got any other question about the bank feel free to ask.
